import { FC } from "react"
import Head from "next/head"

const Home: FC = () => (
    <>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
            Hello
        </main>
    </>
)

export default Home 
